import type { Product } from "@/lib/types";

const now = "2026-05-13T12:00:00.000Z";

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    slug: "japanese-pokemon-151-booster-box",
    name: "Japanese Pokemon 151 Booster Box",
    category: "sealed",
    franchise: "Pokemon",
    setName: "Scarlet & Violet 151",
    language: "Japanese",
    condition: "Sealed",
    price: 189.99,
    quantity: 3,
    status: "listed",
    publicStatus: "listed",
    description: "Factory sealed Japanese Pokemon 151 booster box with shrink intact.",
    conditionNotes: "Sealed box. Light shelf wear possible on outer wrap from storage.",
    imageUrls: ["/products/placeholder-card-1.svg"],
    primaryImageUrl: "/products/placeholder-card-1.svg",
    externalListingUrl: "https://www.ebay.com/",
    externalListingPlatform: "eBay",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-151-box-001",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "prod-002",
    slug: "japanese-pokemon-151-booster-pack",
    name: "Japanese Pokemon 151 Booster Pack",
    category: "sealed",
    franchise: "Pokemon",
    setName: "Scarlet & Violet 151",
    language: "Japanese",
    condition: "Sealed",
    price: 12.99,
    quantity: 24,
    status: "listed",
    publicStatus: "available",
    description: "Single sealed Japanese Pokemon 151 booster pack.",
    conditionNotes: "Pack art and crimp inspected. No visible tears or tampering.",
    imageUrls: ["/products/placeholder-card-2.svg"],
    primaryImageUrl: "/products/placeholder-card-2.svg",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-151-pack-014",
    createdAt: "2026-05-12T10:00:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-003",
    slug: "charizard-ex-single",
    name: "Charizard ex Single",
    category: "single",
    franchise: "Pokemon",
    setName: "Obsidian Flames",
    cardNumber: "125/197",
    isFoil: true,
    language: "English",
    condition: "Near Mint",
    price: 39.99,
    quantity: 1,
    status: "listed",
    publicStatus: "listed",
    description: "Charizard ex pulled and sleeved quickly, listed with actual front photo.",
    conditionNotes: "Near Mint. Minor centering variance visible. No bends or whitening observed.",
    imageUrls: ["/products/placeholder-card-3.svg"],
    primaryImageUrl: "/products/placeholder-card-3.svg",
    externalListingUrl: "https://www.tcgplayer.com/",
    externalListingPlatform: "TCGplayer",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-charizard-ex-003",
    createdAt: "2026-05-10T09:20:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-004",
    slug: "pikachu-promo-single",
    name: "Pikachu Promo Single",
    category: "single",
    franchise: "Pokemon",
    setName: "Promo",
    cardNumber: "SVP-101",
    isFoil: false,
    language: "English",
    condition: "Lightly Played",
    price: 14.99,
    quantity: 1,
    status: "listed",
    publicStatus: "available",
    description: "A clean binder-ready Pikachu promo for collectors building character pages.",
    conditionNotes: "Light edge whitening on back left. Front presents well in binder.",
    imageUrls: ["/products/placeholder-card-4.svg"],
    primaryImageUrl: "/products/placeholder-card-4.svg",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-pikachu-promo-004",
    createdAt: "2026-05-09T18:00:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-005",
    slug: "psa-10-pikachu-slab",
    name: "PSA 10 Pikachu Slab",
    category: "slab",
    franchise: "Pokemon",
    setName: "Crown Zenith",
    language: "English",
    condition: "Graded",
    gradeCompany: "PSA",
    grade: "10",
    price: 129.99,
    quantity: 1,
    status: "listed",
    publicStatus: "listed",
    description: "PSA 10 Pikachu slab with clean case presentation.",
    conditionNotes: "PSA holder is clean with light handling marks only.",
    imageUrls: ["/products/placeholder-card-5.svg"],
    primaryImageUrl: "/products/placeholder-card-5.svg",
    externalListingUrl: "https://www.ebay.com/",
    externalListingPlatform: "eBay",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-psa-pika-005",
    createdAt: "2026-05-08T13:00:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-006",
    slug: "one-piece-sealed-booster-box",
    name: "One Piece Sealed Booster Box",
    category: "sealed",
    franchise: "One Piece",
    setName: "500 Years in the Future",
    language: "English",
    condition: "Sealed",
    price: 119.99,
    quantity: 2,
    status: "listed",
    publicStatus: "available",
    description: "Sealed One Piece booster box ready for collectors or sealed display.",
    conditionNotes: "Sealed box with intact factory wrap. Corners reviewed before shipping.",
    imageUrls: ["/products/placeholder-card-6.svg"],
    primaryImageUrl: "/products/placeholder-card-6.svg",
    actualPhoto: true,
    conditionReviewed: true,
    createdAt: "2026-05-06T15:30:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-013",
    slug: "magic-the-gathering-collector-booster",
    name: "Magic: The Gathering Collector Booster",
    category: "sealed",
    franchise: "Magic: The Gathering",
    setName: "Collector Booster",
    language: "English",
    condition: "Sealed",
    price: 29.99,
    quantity: 8,
    status: "listed",
    publicStatus: "available",
    description: "Sealed Magic: The Gathering collector booster selected for display-ready inventory.",
    conditionNotes: "Factory sealed pack. Wrapper reviewed before shipping.",
    imageUrls: ["/products/placeholder-card-13.svg"],
    primaryImageUrl: "/products/placeholder-card-13.svg",
    actualPhoto: true,
    conditionReviewed: true,
    createdAt: "2026-05-06T12:00:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-007",
    slug: "english-pokemon-elite-trainer-box",
    name: "English Pokemon Elite Trainer Box",
    category: "sealed",
    franchise: "Pokemon",
    setName: "Temporal Forces",
    language: "English",
    condition: "Sealed",
    price: 44.99,
    quantity: 4,
    status: "listed",
    publicStatus: "available",
    description: "Factory sealed Elite Trainer Box with clean shelf presentation.",
    conditionNotes: "Shrink intact. Minor shelf wear possible on exterior wrap.",
    imageUrls: ["/products/placeholder-card-7.svg"],
    primaryImageUrl: "/products/placeholder-card-7.svg",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-etb-007",
    createdAt: "2026-05-05T14:10:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-008",
    slug: "pokemon-binder-lot-bulk-collection",
    name: "Pokemon Binder Lot / Bulk Collection",
    category: "bulk",
    franchise: "Pokemon",
    language: "English",
    condition: "Unknown",
    price: 79.99,
    quantity: 1,
    status: "listed",
    publicStatus: "available",
    description: "Mixed binder and bulk lot with commons, uncommons, rares, and reverse holos.",
    conditionNotes: "Mixed condition from played to near mint. Best for builders, kids, and binder fillers.",
    imageUrls: ["/products/placeholder-card-8.svg"],
    primaryImageUrl: "/products/placeholder-card-8.svg",
    actualPhoto: true,
    conditionReviewed: false,
    scanId: "scan-bulk-008",
    createdAt: "2026-05-04T11:00:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-009",
    slug: "sold-psa-9-mewtwo-slab",
    name: "Sold PSA 9 Mewtwo Slab",
    category: "slab",
    franchise: "Pokemon",
    setName: "Pokemon GO",
    language: "English",
    condition: "Graded",
    gradeCompany: "PSA",
    grade: "9",
    price: 54.99,
    quantity: 0,
    status: "listed",
    publicStatus: "sold",
    description: "Recently sold PSA 9 Mewtwo slab. Kept visible as an example of recent inventory.",
    conditionNotes: "Sold item. Original listing noted a clean holder with light scuffing.",
    imageUrls: ["/products/placeholder-card-9.svg"],
    primaryImageUrl: "/products/placeholder-card-9.svg",
    actualPhoto: true,
    conditionReviewed: true,
    createdAt: "2026-05-02T16:30:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-010",
    slug: "sold-snorlax-single",
    name: "Sold Snorlax Single",
    category: "single",
    franchise: "Pokemon",
    setName: "Pokemon 151",
    cardNumber: "143/165",
    isFoil: false,
    language: "English",
    condition: "Near Mint",
    price: 8.99,
    quantity: 0,
    status: "listed",
    publicStatus: "sold",
    description: "Sold Snorlax single from recent catalog intake.",
    conditionNotes: "Sold item. Near Mint condition reviewed before listing.",
    imageUrls: ["/products/placeholder-card-10.svg"],
    primaryImageUrl: "/products/placeholder-card-10.svg",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-snorlax-010",
    createdAt: "2026-05-01T08:45:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-011",
    slug: "coming-soon-japanese-sealed-product",
    name: "Coming Soon Japanese Sealed Product",
    category: "sealed",
    franchise: "Pokemon",
    language: "Japanese",
    condition: "Sealed",
    quantity: 6,
    status: "listed",
    publicStatus: "coming_soon",
    description: "Japanese sealed product intake is being reviewed before publication.",
    conditionNotes: "Scanner intake complete. Awaiting manual product review and pricing.",
    imageUrls: [],
    primaryImageUrl: "",
    actualPhoto: false,
    conditionReviewed: false,
    scanId: "scan-sealed-coming-011",
    createdAt: "2026-04-30T19:15:00.000Z",
    updatedAt: now
  },
  {
    id: "prod-012",
    slug: "japanese-ar-sar-single",
    name: "Japanese AR/SAR Single",
    category: "single",
    franchise: "Pokemon",
    setName: "Shiny Treasure ex",
    cardNumber: "349/190",
    isFoil: true,
    language: "Japanese",
    condition: "Near Mint",
    price: 24.99,
    quantity: 1,
    status: "listed",
    publicStatus: "available",
    description: "Japanese art rare style single with strong display appeal.",
    conditionNotes: "Near Mint. Fresh sleeve and top loader storage after review.",
    imageUrls: ["/products/placeholder-card-12.svg"],
    primaryImageUrl: "/products/placeholder-card-12.svg",
    actualPhoto: true,
    conditionReviewed: true,
    scanId: "scan-jp-ar-012",
    createdAt: "2026-04-28T12:00:00.000Z",
    updatedAt: now
  }
];
